// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroRealm_Server.Models;

#nullable disable

namespace RetroRealm_Server.Migrations
{
    [DbContext(typeof(RetroRealmDatabaseContext))]
    [Migration("20251130172831_Update20251130")]
    partial class Update20251130
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("RetroRealm_Server.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.BunnyRunStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bunny_Run_Status");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.FlappyBirdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPassedPipes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Flappy_Bird_Status");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.MemoryGameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinFlipping")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Memory_Game_Status");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BunnyRunStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedChallangesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentAvatarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlappyBirdStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemoryCardStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnedAvatarsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordleStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BunnyRunStatusId");

                    b.HasIndex("FlappyBirdStatusId");

                    b.HasIndex("MemoryCardStatusId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("WordleStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.WordleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedWords")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wordle_Status");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.BunnyRunStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.FlappyBirdStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.MemoryGameStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.RefreshToken", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.User", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.BunnyRunStatus", "BunnyRunStatus")
                        .WithMany()
                        .HasForeignKey("BunnyRunStatusId");

                    b.HasOne("RetroRealm_Server.Models.FlappyBirdStatus", "FlappyBirdStatus")
                        .WithMany()
                        .HasForeignKey("FlappyBirdStatusId");

                    b.HasOne("RetroRealm_Server.Models.MemoryGameStatus", "MemoryGameStatus")
                        .WithOne()
                        .HasForeignKey("RetroRealm_Server.Models.User", "MemoryCardStatusId");

                    b.HasOne("RetroRealm_Server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("RetroRealm_Server.Models.WordleStatus", "WorldeStatus")
                        .WithMany()
                        .HasForeignKey("WordleStatusId");

                    b.Navigation("BunnyRunStatus");

                    b.Navigation("FlappyBirdStatus");

                    b.Navigation("MemoryGameStatus");

                    b.Navigation("Role");

                    b.Navigation("WorldeStatus");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.WordleStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
