// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroRealm_Server.Models;

#nullable disable

namespace RetroRealm_Server.Migrations.LogDatabase
{
    [DbContext(typeof(LogDatabaseContext))]
    [Migration("20251128100432_InitialLogMigration")]
    partial class InitialLogMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("RetroRealm_Server.Models.BunnyRunStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BunnyRunStatus");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.FlappyBirdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPassedPipes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlappyBirdStatus");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.MemoryGameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinFlipping")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MemoryGameStatus");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BunnyRunStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedChallangesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentAvatarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlappyBirdStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemoryCardStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnedAvatarsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordleStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BunnyRunStatusId");

                    b.HasIndex("FlappyBirdStatusId");

                    b.HasIndex("MemoryCardStatusId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("WordleStatusId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.WordleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedWords")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WordleStatus");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.BunnyRunStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.FlappyBirdStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Log", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.MemoryGameStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.User", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.BunnyRunStatus", "BunnyRunStatus")
                        .WithMany()
                        .HasForeignKey("BunnyRunStatusId");

                    b.HasOne("RetroRealm_Server.Models.FlappyBirdStatus", "FlappyBirdStatus")
                        .WithMany()
                        .HasForeignKey("FlappyBirdStatusId");

                    b.HasOne("RetroRealm_Server.Models.MemoryGameStatus", "MemoryGameStatus")
                        .WithOne()
                        .HasForeignKey("RetroRealm_Server.Models.User", "MemoryCardStatusId");

                    b.HasOne("RetroRealm_Server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("RetroRealm_Server.Models.WordleStatus", "WorldeStatus")
                        .WithMany()
                        .HasForeignKey("WordleStatusId");

                    b.Navigation("BunnyRunStatus");

                    b.Navigation("FlappyBirdStatus");

                    b.Navigation("MemoryGameStatus");

                    b.Navigation("Role");

                    b.Navigation("WorldeStatus");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.WordleStatus", b =>
                {
                    b.HasOne("RetroRealm_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroRealm_Server.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
